import {useCallback,useEffect,useMemo,useRef,useState,type ChangeEvent} from 'react';
import {createInferenceWorker} from '@practics/tryon-core/workers';
import {renderOutfitTryOn,type Accelerator,type GarmentAnchors,type HemLength,type PipelineResult,type PartialTryOnConfig} from '@practics/tryon-core';

type Garment={id:string;name:string;image:string;color:string;occasion:string[];styles:string[];sleeves?: 'full'|'half'|'sleeveless';length:HemLength;anchors:GarmentAnchors;description:string};
const garments:Garment[]=[
{id:'white',name:'Clean White Shirt',image:'/garments/white-shirt.svg',color:'White',occasion:['casual','college','office','date','travel'],styles:['Minimal','Classic','Smart Casual'],sleeves:'full',length:'hip',anchors:{shoulderL:[115,65],shoulderR:[485,65],waistL:[155,500],waistR:[445,500],hemL:[145,720],hemR:[455,720]},description:'Crisp and versatile.'},
{id:'navy',name:'Navy Overshirt',image:'/garments/navy-overshirt.svg',color:'Navy',occasion:['casual','college','travel','date'],styles:['Minimal','Streetwear','Smart Casual'],sleeves:'full',length:'hip',anchors:{shoulderL:[100,70],shoulderR:[500,70],waistL:[145,505],waistR:[455,505],hemL:[130,730],hemR:[470,730]},description:'Relaxed utility layer.'},
{id:'black',name:'Black Evening Shirt',image:'/garments/black-shirt.svg',color:'Black',occasion:['date','party','office','formal'],styles:['Minimal','Elegant','Classic'],sleeves:'full',length:'hip',anchors:{shoulderL:[112,62],shoulderR:[488,62],waistL:[150,500],waistR:[450,500],hemL:[142,720],hemR:[458,720]},description:'Clean evening silhouette.'},
{id:'olive',name:'Olive Utility Shirt',image:'/garments/olive-shirt.svg',color:'Olive',occasion:['casual','college','travel'],styles:['Streetwear','Minimal','Sporty'],sleeves:'full',length:'hip',anchors:{shoulderL:[105,70],shoulderR:[495,70],waistL:[145,500],waistR:[455,500],hemL:[130,725],hemR:[470,725]},description:'Earthy and easy-going.'},
{id:'cream',name:'Modern Cream Kurta',image:'/garments/cream-kurta.svg',color:'Cream',occasion:['wedding','party','formal','date'],styles:['Elegant','Classic','Minimal'],sleeves:'full',length:'knee',anchors:{shoulderL:[115,55],shoulderR:[485,55],waistL:[145,485],waistR:[455,485],hemL:[105,930],hemR:[495,930]},description:'Festive Indian-inspired look.'},
{id:'burgundy',name:'Burgundy Statement Shirt',image:'/garments/burgundy-shirt.svg',color:'Burgundy',occasion:['party','date','wedding'],styles:['Elegant','Streetwear'],sleeves:'full',length:'hip',anchors:{shoulderL:[110,65],shoulderR:[490,65],waistL:[150,500],waistR:[450,500],hemL:[140,725],hemR:[460,725]},description:'A richer statement option.'}
];
const occasions=['casual','college','office','date','party','wedding','formal','travel'];
const styles=['Minimal','Classic','Streetwear','Smart Casual','Elegant','Sporty'];
const weather=['Hot','Warm','Cool','Cold','Rainy'];
const config:PartialTryOnConfig={minKeypointScore:.3,anchors:{widthScale:{shoulder:1.15,hip:1.45},shoulderLift:.05,waistT:.62,hemFallbackMultiplier:{hip:.15,knee:1,ankle:1.9},skirtFlare:{hip:1,knee:1.9,ankle:2.6},dressFlare:{hip:1,knee:1.2,ankle:1.35},stanceCoverMargin:.25,stanceScoreSoftBand:.15},warpGrid:{cols:16,rows:24},armOcclusionRadiusFactor:.14};
const assetUrl=(p:string)=>/^[a-z][a-z0-9+.-]*:/i.test(p)?p:import.meta.env.BASE_URL.replace(/\/$/,'')+p;

export default function App(){
 const [photo,setPhoto]=useState<ImageBitmap|null>(null),[result,setResult]=useState<PipelineResult|null>(null),[processing,setProcessing]=useState(false),[status,setStatus]=useState('Choose a photo to start'),[accelerator,setAccelerator]=useState<Accelerator>('webgpu'),[backend,setBackend]=useState<Accelerator|null>(null),[error,setError]=useState('');
 const [occasion,setOccasion]=useState('casual'),[style,setStyle]=useState('Minimal'),[temp,setTemp]=useState('Warm'),[selected,setSelected]=useState<Garment|null>(null),[garmentImage,setGarmentImage]=useState<ImageBitmap|null>(null);
 const canvasRef=useRef<HTMLCanvasElement>(null),workerRef=useRef<Worker|null>(null),seq=useRef(0),pending=useRef(new Map<number,{resolve:(x:PipelineResult)=>void,reject:(e:Error)=>void}>());
 const recommended=useMemo(()=>{const a=garments.filter(g=>g.occasion.includes(occasion)&&g.styles.includes(style));const b=garments.filter(g=>g.occasion.includes(occasion));return [...a,...b].filter((g,i,x)=>x.findIndex(v=>v.id===g.id)===i).slice(0,4)},[occasion,style]);
 useEffect(()=>{if(!selected&&recommended[0])setSelected(recommended[0])},[recommended,selected]);

 useEffect(()=>{const w=createInferenceWorker();workerRef.current=w;setBackend(null);setError('');w.onmessage=(e:MessageEvent<any>)=>{const m=e.data;if(m.type==='ready'){setBackend(m.backend);setStatus(`AI ready • ${m.backend==='webgpu'?'GPU':'CPU'}`)}else if(m.type==='result'){const p=pending.current.get(m.seq);if(p){pending.current.delete(m.seq);p.resolve({keypoints:m.keypoints,maskBitmap:m.maskBitmap,timings:m.timings})}}else if(m.seq!==undefined){const p=pending.current.get(m.seq);if(p){pending.current.delete(m.seq);p.reject(new Error(m.message))}}else setError(m.message||'AI worker error')};w.onerror=e=>setError(e.message||'AI worker failed');w.postMessage({type:'init',wasmPath:assetUrl('/litert-wasm/'),modelPaths:{segmenter:assetUrl('/models/selfie_segmenter.tflite'),pose:assetUrl('/models/movenet_singlepose_lightning.tflite')},accelerator});return()=>{w.terminate();workerRef.current=null;pending.current.clear()}},[accelerator]);

 const analyze=useCallback(async(b:ImageBitmap)=>{const w=workerRef.current;if(!w){setError('AI engine is still loading.');return}setProcessing(true);setError('');setStatus('Analyzing pose and body mask on this device…');const copy=await createImageBitmap(b),n=++seq.current;const p=new Promise<PipelineResult>((resolve,reject)=>{pending.current.set(n,{resolve,reject});setTimeout(()=>{const x=pending.current.get(n);if(x){pending.current.delete(n);reject(new Error('AI inference timed out.'))}},30000)});w.postMessage({type:'process',bitmap:copy,seq:n},[copy]);try{const r=await p;setResult(r);setStatus('Analysis complete • ready for try-on')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setProcessing(false)}},[]);

 const onFile=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>15*1024*1024){setError('Photo must be under 15 MB.');return}try{const b=await createImageBitmap(f);photo?.close();setPhoto(b);setResult(null);await analyze(b)}catch(err){setError(err instanceof Error?err.message:'Could not read photo')}e.target.value=''};

 useEffect(()=>{if(!selected)return;let dead=false;(async()=>{try{const r=await fetch(assetUrl(selected.image));if(!r.ok)throw new Error();const im=await createImageBitmap(await r.blob());if(dead)im.close();else{garmentImage?.close();setGarmentImage(im)}}catch{setError('Could not load outfit asset.')}})();return()=>{dead=true}},[selected]);

 useEffect(()=>{const c=canvasRef.current;if(!c||!photo)return;c.width=photo.width;c.height=photo.height;const ctx=c.getContext('2d');if(!ctx)return;ctx.drawImage(photo,0,0);if(result&&garmentImage&&selected){renderOutfitTryOn(ctx,{frame:photo,maskBitmap:result.maskBitmap,keypoints:result.keypoints,top:{image:garmentImage,anchors:selected.anchors,hemLength:selected.length},pants:null,config})}},[photo,result,garmentImage,selected]);

 const save=()=>{const c=canvasRef.current;if(!c||!photo||!result)return;const a=document.createElement('a');a.download='stylo-try-on.png';a.href=c.toDataURL('image/png');a.click();setStatus('PNG saved ✓')};
 const retry=()=>{if(photo)analyze(photo)};

 return <div className="app"><header><div><div className="brand">Stylo</div><div className="tag">PERSONAL FASHION STUDIO</div></div><div className="privacy">🔒 ON-DEVICE AI</div></header><main>
 <section className="hero"><div><span className="pill">100% free • no API key</span><h1>See yourself <em>in the look.</em></h1><p>Upload one photo. Stylo uses on-device AI to understand your pose and warp the selected outfit to your body. Your photo is processed in your browser.</p><label className="upload"><input type="file" accept="image/*" onChange={onFile}/><span>📷 <b>{photo?'Change photo':'Upload your photo'}</b><small>JPG, PNG or WEBP • max 15 MB</small></span></label>{error&&<div className="error">{error}<button onClick={()=>setAccelerator(accelerator==='webgpu'?'wasm':'webgpu')}>Try {accelerator==='webgpu'?'CPU':'GPU'} mode</button></div>}</div>
 <div className="stage"><div className="stage-head"><b>How will I look?</b><span>{processing?'AI WORKING…':backend?'AI READY':'LOADING AI…'}</span></div><div className="canvas-box">{photo?<canvas ref={canvasRef}/>:<div className="empty-stage"><span>✦</span><b>Your preview appears here</b><small>Upload a photo and choose a look.</small></div>}</div><div className="stage-actions"><button className="primary" disabled={!photo||!result||!garmentImage||processing} onClick={save}>↓ Save look</button><button disabled={!photo||processing} onClick={retry}>↻ Re-analyze</button></div></div></section>
 <section className="controls"><div className="control"><label>Occasion</label><div className="chips">{occasions.map(x=><button className={occasion===x?'active':''} onClick={()=>setOccasion(x)} key={x}>{x}</button>)}</div></div><div className="control"><label>Your style</label><div className="chips">{styles.map(x=><button className={style===x?'active':''} onClick={()=>setStyle(x)} key={x}>{x}</button>)}</div></div><div className="mini"><label>Weather</label><select value={temp} onChange={e=>setTemp(e.target.value)}>{weather.map(x=><option key={x}>{x}</option>)}</select></div></section>
 <section className="recommend"><div className="section-title"><div><span>PERSONALIZED PICKS</span><h2>Try these looks</h2></div><small>{recommended.length} matches</small></div><div className="cards">{recommended.map(g=><button className={'look-card '+(selected?.id===g.id?'selected':'')} key={g.id} onClick={()=>setSelected(g)}><div className="garment-art"><img src={assetUrl(g.image)} /></div><div className="look-info"><span>{g.color}</span><h3>{g.name}</h3><p>{g.description}</p><b>{selected?.id===g.id?'✓ Selected':'Try this look →'}</b></div></button>)}</div></section>
 <section className="trust"><div>🧠 <b>AI runs on your device</b><span>No photo upload or paid API.</span></div><div>⚡ <b>WebGPU when available</b><span>CPU fallback included.</span></div><div>💾 <b>Your photo stays local</b><span>Nothing is sent to Stylo.</span></div></section>
 </main><footer>Stylo • on-device virtual try-on • ₹0 API cost</footer></div>;
}